# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "lib" ]
  pull_request:
    branches: [ "lib" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v6
      with: { go-version: stable }

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    # Examples
    - run: go test -v ./_examples/library
    - run: go build -o /dev/null ./_examples/library/basic
    - run: go build -o /dev/null ./_examples/library/s3
    - run: go build -o /dev/null ./_examples/library/vfs
